dataset_name: "MNIST"
train_images_file_path: "mnist_data/train-images-idx3-ubyte.gz"
train_labels_file_path: "mnist_data/train-labels-idx1-ubyte.gz"
val_images_file_path: "mnist_data/t10k-images-idx3-ubyte.gz"
val_labels_file_path: "mnist_data/t10k-labels-idx1-ubyte.gz"
